### ISSUE TITLE
Consider enabling some more options.

### ISSUE THREAD

**Issue by plugwash** [hexdump0815/kernel-config-options#2]
First off thank you for providing an up to date image for the odroid u2. I have an odroid u2 which I use as a buildbox, and which was previously on wheezy with the odriod vendor kernel, this was becoming increasingly untenable, so I reinstalled it with your image.

Unfortunately I ran into a couple of issues, the first is that iotop doesn't work. It fails with.

    root@odroidu2:~# iotop
    Could not run iotop as some of the requirements are not met:
    - Linux >= 2.6.20 with
      - I/O accounting support (CONFIG_TASKSTATS, CONFIG_TASK_DELAY_ACCT, CONFIG_TASK_IO_ACCOUNTING)
    root@odroidu2:~#

The second is that openvpn doesn't work, because the tuntap driver is missing. I believe the required option is CONFIG_TUN.

I'm currently in the process of attempting to follow your kernel build instructions and build a kernel with these options enabled. I will report back with whether it works or not.

**Comment by plugwash** [comment]
Ok, after testing I found I also needed to set CONFIG_TASK_XACCT which CONFIG_TASK_IO_ACCOUNTING depends on, otherwise make olddefconfig ignores the option.

With that done I now have both iotop and openvpn working on my odroid u2 with a 5.18.12 kernel.

    --- a/additional-options-generic.cfg
    +++ b/additional-options-generic.cfg
    @@ -188,3 +188,10 @@ CONFIG_LRU_GEN=y
     CONFIG_LRU_GEN_ENABLED=y
     # bluetooth network support
     CONFIG_BT_BNEP=m
    +# iotop support
    +CONFIG_TASKSTATS=y
    +CONFIG_TASK_DELAY_ACCT=y
    +CONFIG_TASK_XACCT=y
    +CONFIG_TASK_IO_ACCOUNTING=y
    +# vpn support
    +CONFIG_TUN=m

**Comment by hexdump0815** [comment]
@plugwash - thanks for the hint (and for the thanks too) - they seem to be enabled in a default debian kernel, so no problem from my side - i just enabled them: https://github.com/hexdump0815/kernel-config-options/commit/18de2c0c59e5ca5897474f4da7377a1244a9230b so that future kernels should have them

best wishes - hexdump
