### ISSUE TITLE
armv7l config - enable CONFIG_BPF_SYSCALL

### ISSUE THREAD

**Issue by BKPepe** [hexdump0815/kernel-config-options#3]
Hello,

I flashed [220824-01](https://github.com/hexdump0815/imagebuilder/releases/tag/220824-01) on Odroid U3, wanted to install Home Assistant [via docker](https://www.home-assistant.io/installation/odroid#docker-compose) and it failed with:

```
Error response from daemon: Cannot restart container homeassistant: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: bpf_prog_query(BPF_CGROUP_DEVICE) failed: function not implemented: unknown
```

I found that it is related to this issue in Alpine Aports:
https://gitlab.alpinelinux.org/alpine/aports/-/issues/13549

I've checked that CONFIG_BPF_SYSCALL is indeed not set.

```
linux@odroid:~$ cat /boot/config-5.19.1-stb-exy+ | grep CONFIG_BPF
CONFIG_BPF=y
# CONFIG_BPF_SYSCALL is not set
# CONFIG_BPF_JIT is not set
# CONFIG_BPFILTER is not set
```

Would it be please possible to enable it?

Thanks!

**Comment by hexdump0815** [comment]
@BKPepe - i'll put it onto my todo list to add it for future kernels

**Comment by hexdump0815** [comment]
@BKPepe - i have added it to the kernel config options used for future kernels now: https://github.com/hexdump0815/kernel-config-options/commit/90017556f6e315cda3f39565d6edbfa0071bec89
